version: "3.0"
services:
  Simbir_DB:
    container_name: "Simbir_DB"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge