"""initial

Revision ID: 42683bdf13eb
Revises: 
Create Date: 2023-10-31 12:37:30.805721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42683bdf13eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TransportModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TransportType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canBeRented', sa.Boolean(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('minutePrice', sa.Float(), nullable=True),
    sa.Column('dayPrice', sa.Float(), nullable=True),
    sa.Column('colorId', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('transportTypeId', sa.Integer(), nullable=False),
    sa.Column('transportModelId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colorId'], ['Color.id'], ),
    sa.ForeignKeyConstraint(['ownerId'], ['User.id'], ),
    sa.ForeignKeyConstraint(['transportModelId'], ['TransportModel.id'], ),
    sa.ForeignKeyConstraint(['transportTypeId'], ['TransportType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transport')
    op.drop_table('User')
    op.drop_table('TransportType')
    op.drop_table('TransportModel')
    op.drop_table('Color')
    # ### end Alembic commands ###
